cc_test(
    name = "constexpr_for",
    size = "large",
    srcs = [
        "constexpr_for_test.cc",
    ],
    deps = [
        "//:CEXForLoop",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "constexpr_for_functional",
    size = "large",
    srcs = [
        "constexpr_for_functional_test.cc",
    ],
    deps = [
        "//:CEXForLoop",
        "@googletest//:gtest_main",
    ],
)
