cc_test(
    name = "constexpr_for",
    size = "large",
    srcs = [
        "constexpr_for_test.cc",
    ],
    deps = [
        "//include:CEXForLoop",
        "@googletest//:gtest_main",
    ],
)
