cc_library(
    name = "CEXForLoop",
    srcs = glob(["impl/*.h"]),
    hdrs = [
        "cex_for_loop.h",
        "bool_expression_functors.h",
    ],
    visibility = ["//visibility:public"],
    deps = [],
)
